doctor/urls.py
from django.urls import path
from . import views

app_name = 'doctor'


urlpatterns = [
    path('', views.index,name="index"),
    path('login', views.doctor_login,name="login"),
    path('signup', views.doctor_signup,name="signup")
    
]

fb/urls.py
from django.urls import path
from . import views


app_name='fb'

urlpatterns = [
    path('fb', views.fb, name='fb_login')
]

home/urls.py
from django.urls import path
from . import views



app_name = 'home' 



urlpatterns = [
    path('', views.home, name='home_index')
]

hospital_admin/urls.py
from django.urls import path
from . import views


app_name='hadmin'


urlpatterns =[
    path('', views.admin_index, name='index'),
    path('login/', views.admin_login, name='log_in'),
    path('signup/' ,views.admin_signup, name='signup')
]

hospital_management/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('home.urls')),
    path('fb/', include('fb.urls')),
    path('admin/', admin.site.urls),
    path('doctor/', include('doctor.urls')),
    path('patient/', include('patient.urls')),
    path('hospital_admin/', include('hospital_admin.urls'))
]

patient/urls.py
from django.urls import path
from . import views


app_name = 'patient'



urlpatterns = [
    path('patient/', views.patient_signup, name='patient_signup'),
    path('', views.patient_home, name='patient_home'),
    path('signup/', views.patient_login, name='patient_login')
]

doctor/models.py
from django.db import models

# Create your models here.

fb/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

hospital_admin/models.py
from django.db import models

# Create your models here.

patient/models.py
from django.db import models

# Create your models here.

doctor/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.


# def index(request):
    # return HttpResponse("Welcome to Doctor's Page")


def index(request):
    return render(request,"doctor_templates/doctor.html")


def doctor_login(request):
    return render(request,"doctor_templates/login.html")
    

def doctor_signup(request):
    return render(request, "doctor_templates/signup.html")

fb/views.py
from django.shortcuts import render

# Create your views here.

def fb (request):
    return render(request, 'fb_templates/fb_login.html')

home/views.py
from django.shortcuts import render

# Create your views here.


def home(request):
    return render(request, 'home_templates/home.html')

hospital_admin/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def admin_index(request):
    return render(request, 'admin_templates/admin_home.html')

def admin_login(request):
    return render(request, 'admin_templates/admin_login.html')

def admin_signup(request):
    return render(request, 'admin_templates/admin_signup.html')

patient/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def patient_signup(request):
    return render(request, 'patient_tempates/patient_signup.html')

def patient_home(request):
    return render(request, 'patient_tempates/patient_home.html')

def patient_login(request):
    return render(request, 'patient_tempates/patient_login.html')

doctor/templates/doctor_templates/doctor.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Welcome Doctors</h1><br><br>
    <img src="{% static 'images/doctor 1.jpg' %}" alt="">
    <a href="{% url 'doctor:login' %}"><input type="button" value="Take me to login Page"></a>
    <a href="{% url 'doctor:signup' %}"><input type="button" value="Take me to Signup Page"></a>
</body>
</html>

doctor/templates/doctor_templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Log in</h1> <br>
    <input type="text" placeholder="Enter your E-mail address">
    <input type="password" placeholder="Enter your Password here">
    <a href="{% url 'doctor:index' %}"><input type="button" value="login"></a><br>
    <img src="{% static 'images/doctor 1.jpg' %}" alt="">
</body>
</html>

doctor/templates/doctor_templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Sign Up</h1><br>
    <input type="text" placeholder="Enter your email id">
    <input type="password" placeholder="Create your password">
    <input type="button" value="Sign Up">
</body>
</html>

fb/templates/fb_templates/fb_login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Facebook Login</title>
</head>

<body>
    <table  width="100%" cellspacing="0">
        <tr bgcolor="#3333ff">
            <th width="50%" align="left" style="color:white ;">
                <label  ><img width="150px" src="{% static 'images\facebook.jpg' %}" alt=""></label>
            </th>
            <th >
                <form action="">
                    <input size="10px" type="text">
                    <input size="10px" type="password">
                    <input type="button" value="Login">
                </form>
            </th>
        </tr>
        <tr bgcolor="#e6ffff">
            <td>
                <table width="100%">
                    <tr>
                        <td style="font-size:20px; font-weight:bolder;"><br>
                            <label>Connect with friends and the world</label>
                            <label>around you on Facebook</label>
                        </td>
                    </tr>
                    <td>
                        <form action="">
                            <br><br>
                            <img src="{% static 'images\feed.jpg' %}" alt="image can be loaded" width="20px" height="20px">
                            <label style="font-size: 14px; font-weight: bold;" for="">See photos and updates from
                                friends in news feed</label>
                            <br><img src="{% static 'images\share.jpg' %}" alt="image can be loaded" height="20px">
                            <label style="font-size: 14px; font-weight: bold;" for="">
                                share whats new on your life on time line
                            </label>
                            <label style="font-size: 14px; font-weight: bold;" for="">
                                <br><img src="{% static 'images\star.jpg' %}" alt="image can be loaded" height="20px">
                                Find more of what you're looking for with Graph search
                            </label>
                        </form>
                    </td>
                    <tr>
                    </tr>
                </table>
                <td align="left">
                    <table align="center" >
                        <th>
                            <label for="">Sign Up</label><br>
                        </th>
                        
                    </table>
                    
                    <form action="">
                        
                        <input placeholder="First Name" size="7px" type="text">
                        <input placeholder="Surname" size="25x" type="text"><br>
                        <br><input placeholder="Phone Number" size="38px" type="text">
                        <br><br><input placeholder="Email" size="38px" type="text">
                        <br><br><input placeholder="Password" size="38px" type="password"><br>
                        <br><input  type="button" value="Sign Up">
                    </form>
                </td>
            </td>
        </tr>
    </table>
</body>

</html>

home/templates/home_templates/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Welcome to Hospital</h1>
    <br><br>
    <a href="{% url 'doctor:index'%}"><input type="button" value="Doctor"></a>
    <a href="{% url 'patient:patient_home' %}"><input type="button" value="Patient"></a>
    <a href="{% url 'hadmin:index'%}"><input type="button" value="Hospital Admin"></a>
    <a href="{% url 'fb:fb_login' %}"><input type="button" value="Fb"></a>

</body>
</html>

hospital_admin/templates/admin_templates/admin_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Welcome Admins</h1>
    <a href="{% url 'hadmin:signup' %}"><input type="button" value="Take me to sign up Page"></a>
    <a href="{% url 'hadmin:log_in' %}"><input type="button" value="Take me to Login Page"></a>
</body>
</html>

hospital_admin/templates/admin_templates/admin_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Log In</h1><br>
    <input type="text" placeholder="Enter your E-mail address">
    <input type="password" placeholder="Enter the password">
    <input type="button" value="Log In">
</body>
</html>

hospital_admin/templates/admin_templates/admin_signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Sign Up</h1>
    <input type="text" placeholder="Enter the Email address">
    <input type="password" placeholder="Enter the password here">
    <input type="button" value="Sign Up">
</body>
</html>

hospital_management/templates/home_templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    welcome
</body>
</html>

patient/templates/patient_tempates/patient_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Welcome Patients</h1>
    <a href="{% url 'patient:patient_signup' %}"><input type="button" value="Take me to the Sign up Page"></a>
    <a href="{% url 'patient:patient_login' %}"><input type="button" value="Take me to the Log in page"></a>
</body>
</html>

patient/templates/patient_tempates/patient_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Welcome to the Log in page</h1>

    <input type="text" placeholder="Enter the E-mail address">
    <input type="password" placeholder="Create Password here">
    <input type="button" value="Log in">
</body>
</html>

patient/templates/patient_tempates/patient_signup.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Welcome to Patients page</h1>
    <h4>Sign Up</h4>
    <input type="text" placeholder="Enter your E-mail ID">
    <input type="password" placeholder="Create Password">
    <input type="button" value="Sign Up"><br><br>
    <img src="{% static 'images/doctor 2.jpg'%}" alt="">
    
    
</body>
</html>